//
// This file is part of Hecios
//
// Copyright (C) 2007,2008,2009 Brad Settlemyer
//
// This file is distributed WITHOUT ANY WARRANTY. See the file 'License.txt'
// for details on this and other legal matters.
//

//
// Module responsible for translating file system blocks to physical hardware
// addresses
//
simple BlockTranslator
  gates:
    in: in, response;
    out: out, request;
endsimple



